openapi: 3.0.0
info:
  title: brew-note api
  version: 0.0.1
servers:
- url: /
tags:
- description: Brew Note 関連のAPI
  name: brew-note
paths:
  /me:
    get:
      description: ログイン中のUser情報を返します
      operationId: getProfile
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ok
        "500":
          description: InternalServerError
      security:
      - Brew-Note-Auth-Token: []
      summary: Get Profile
      tags:
      - brew-ntoe
  /users:
    get:
      description: user一覧を取得します。
      operationId: getUsers
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: ok
        "500":
          description: InternalServerError
      summary: Get Users
      tags:
      - brew-ntoe
  /beans:
    get:
      description: bean一覧を取得します。
      operationId: getBeans
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Bean'
                type: array
          description: ok
        "500":
          description: Internal Server Error
      summary: Get Beans
      tags:
      - brew-note
    post:
      description: Bean情報を登録します
      operationId: createBean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBean'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bean'
          description: ok
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Create Bean
      tags:
      - brew-note
  /roast-levels:
    get:
      description: roast level一覧を取得します。
      operationId: getRoastLevels
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/RoastLevel'
                type: array
          description: ok
        "500":
          description: Internal Server Error
      summary: Get Roast Levels
      tags:
      - brew-note
  /recipes:
    get:
      description: レシピ一覧を取得します
      operationId: getRecipes
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Recipe'
                type: array
          description: ok
        "500":
          description: Internal Server Error
      summary: Get Recipes
      tags:
      - brew-note
components:
  schemas:
    User:
      example:
        name: name
        nickname: nickname
        id: id
        email: email
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        nickname:
          type: string
    Bean:
      example:
        productionArea: productionArea
        kind: kind
        price: 6.027456183070403
        roastLevelId: 0.8008281904610115
        id: id
        beanId: beanId
      properties:
        id:
          type: string
        beanId:
          type: string
        productionArea:
          type: string
        kind:
          type: string
        roastLevelId:
          type: number
        price:
          format: double
          nullable: true
          type: number
      required:
      - beanId
      - id
      - kind
      - price
      - productionArea
      - roastLevelId
    CreateBean:
      example:
        productionArea: productionArea
        kind: kind
        price: 6
        gram: 1
        roastLevelId: 0
      properties:
        productionArea:
          type: string
        kind:
          type: string
        roastLevelId:
          type: integer
        price:
          type: integer
        gram:
          type: integer
      required:
      - kind
      - productionArea
      - roastLevelId
      type: object
    RoastLevel:
      example:
        level: 6.027456183070403
        name: name
        id: 0.8008281904610115
      properties:
        id:
          type: number
        level:
          type: number
        name:
          type: string
      required:
      - id
      - level
      - name
    Recipe:
      example:
        coffeeType: coffeeType
        extractionEquipment: extractionEquipment
        id: 0.8008281904610115
        steps:
        - seconds: 5.637376656633329
          extractionTemperature: 5.962133916683182
          memo: memo
          id: 6.027456183070403
          stepNumber: 1.4658129805029452
        - seconds: 5.637376656633329
          extractionTemperature: 5.962133916683182
          memo: memo
          id: 6.027456183070403
          stepNumber: 1.4658129805029452
      properties:
        id:
          type: number
        extractionEquipment:
          type: string
        coffeeType:
          type: string
        steps:
          items:
            $ref: '#/components/schemas/RecipeStep'
          type: array
      required:
      - coffeeType
      - extractionEquipment
      - id
      - steps
    RecipeStep:
      example:
        seconds: 5.637376656633329
        extractionTemperature: 5.962133916683182
        memo: memo
        id: 6.027456183070403
        stepNumber: 1.4658129805029452
      properties:
        id:
          type: number
        stepNumber:
          type: number
        memo:
          type: string
        extractionTemperature:
          type: number
        seconds:
          type: number
      required:
      - extractionTemperature
      - id
      - memo
      - seconds
      - stepNumber
